### ISSUE TITLE
Add Board Switching

### ISSUE THREAD

**Issue by weihanli101** [weihanli101/workspace#10]
- Switch Boards when you click buttons in navbar
- this requires creating our own Window objects (using Gridster's existing interface) and letting Board objects contain instances of these window objects

**Comment by thechausenone** [comment]
use this resource: https://www.namekdev.net/2017/05/angular-2-my-solution-for-dynamic-tabs/

**Comment by thechausenone** [comment]
this user story requires #18 Create Data Service to be completed first
