### ISSUE TITLE
Window Mapping

### ISSUE THREAD

**Issue by jiwankang** [weihanli101/workspace#29]
Figure out how to map the window to specific programs.
Now task is to open the programs.

(OPENING)

**Comment by jiwankang** [comment]
Going to split this up into opening the programs and resizing them, I should be able to do the first one.

**Comment by jiwankang** [comment]
Waiting until we finish some ui for actually selecting and opening a board (probably #32)

**Comment by thechausenone** [comment]
Going to close this issue and split into two new issues
